apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2018-12-15T19:54:53Z
  name: hello-pod
  namespace: default
  resourceVersion: "546397"
  selfLink: /api/v1/namespaces/default/pods/hello-pod
  uid: 49feee7d-00a3-11e9-af98-08d0f8f11711
spec:
  containers:
  - image: hela:8443/hello-k8s:v1
    imagePullPolicy: IfNotPresent
    name: hello-app
    ports:
    - containerPort: 8080
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-nksb4
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: dpr-secret
  nodeName: minikube
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-nksb4
    secret:
      defaultMode: 420
      secretName: default-token-nksb4
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-12-15T19:54:53Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-12-15T19:54:57Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-12-15T19:54:53Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://7adc075880dd21cd9775b2bad9bde2ed795a05ccbe1dae289f0e1d30b2a4a888
    image: hela:8443/hello-k8s:v1
    imageID: docker-pullable://hela:8443/hello-k8s@sha256:036874a2767bcbbb755ca91fca74508e7e6fdaafa1d84977e2e8ad6aa969daa5
    lastState: {}
    name: hello-app
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2018-12-15T19:54:56Z
  hostIP: 192.168.122.157
  phase: Running
  podIP: 172.17.0.10
  qosClass: BestEffort
  startTime: 2018-12-15T19:54:53Z
